# Generated by Django 4.0.1 on 2023-04-24 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_registration',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='student_registration',
            old_name='First_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='student_registration',
            old_name='Last_name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='student_registration',
            old_name='Roll_no',
            new_name='roll_no',
        ),
    ]
